"""Code generation from route definitions"""

import json
from datetime import datetime
from jinja2 import Template
from typing import List
from .models import RouteDefinition, GeneratedRoute, RoutePattern, TestResult

class RouteCodeGenerator:
    """Generates production-ready route code from definitions"""
    
    SUPERVISOR_MANAGER_TEMPLATE = '''# /routes/{{ route_name }}/route.py
# AUTO-GENERATED by SAFE Route Writer Agent
# DO NOT EDIT - use: safe route update {{ route_name }}

from datetime import datetime
from typing import Dict, Any
import logging
from semantic_kernel import Kernel

logger = logging.getLogger(__name__)

class {{ class_name }}Route:
    """
    {{ route_name }} - {{ description }}
    
    Pattern: {{ pattern }}
    Agents: {{ agent_names }}
    Created: {{ created_at }}
    """
    
    def __init__(self, kernel: Kernel):
        self.kernel = kernel
        {% for agent_key, agent in agents.items() %}
        self.{{ agent_key }} = None  # Initialize {{ agent.name }}
        {% endfor %}
    
    async def invoke(self, request: Dict[str, Any]) -> Dict[str, Any]:
        """Execute {{ route_name }} workflow"""
        start_time = datetime.now()
        
        try:
            # Validate input
            await self._validate_input(request)
            logger.info(f"Processing request for {{ route_name }}")
            
            # Route to supervisor
            supervisor_output = await self.{{ supervisor_key }}.invoke(request)
            
            # Route to appropriate specialist
            routing_field = supervisor_output.get('{{ routing_field }}')
            
            {% for specialist_key, specialist in specialists.items() %}
            {% if loop.first %}if{% else %}elif{% endif %} routing_field == '{{ specialist_key }}':
                result = await self.{{ specialist_key }}.invoke(request)
            {% endfor %}
            else:
                raise ValueError(f"Unknown routing: {routing_field}")
            
            # Aggregate results
            final_output = await self.{{ aggregator_key }}.invoke(result)
            
            # Validate output
            await self._validate_output(final_output)
            
            elapsed = (datetime.now() - start_time).total_seconds()
            logger.info(f"Completed in {elapsed}s")
            
            return final_output
        
        except Exception as e:
            logger.error(f"Route failed: {str(e)}", exc_info=True)
            raise
    
    async def _validate_input(self, request: Dict[str, Any]) -> None:
        """Validate input against contract"""
        required_fields = {{ required_input_fields }}
        for field in required_fields:
            if field not in request:
                raise ValueError(f"Missing required field: {field}")
    
    async def _validate_output(self, output: Dict[str, Any]) -> None:
        """Validate output against contract"""
        required_fields = {{ required_output_fields }}
        for field in required_fields:
            if field not in output:
                raise ValueError(f"Missing required output field: {field}")
'''
    
    @staticmethod
    def generate(route_def: RouteDefinition) -> GeneratedRoute:
        """Generate complete route from definition"""
        
        if route_def.pattern == RoutePattern.SUPERVISOR_MANAGER:
            return RouteCodeGenerator._generate_supervisor_manager(route_def)
        else:
            raise NotImplementedError(f"Pattern {route_def.pattern} not yet implemented")
    
    @staticmethod
    def _generate_supervisor_manager(route_def: RouteDefinition) -> GeneratedRoute:
        """Generate supervisor-manager pattern"""
        
        # Prepare template context
        supervisor_key = "supervisor"
        specialists = {k: v for k, v in route_def.agents.items() if k.startswith("specialist_")}
        aggregator_key = "aggregator"
        
        # Get required fields from supervisor output
        supervisor = route_def.agents[supervisor_key]
        supervisor_required = supervisor.output_schema.get("required", [])
        
        # Get required input fields
        supervisor_input = route_def.agents[supervisor_key].input_schema
        input_required = supervisor_input.get("required", [])
        
        # Get required output fields
        aggregator = route_def.agents[aggregator_key]
        output_required = aggregator.output_schema.get("required", [])
        
        context = {
            "route_name": route_def.name,
            "class_name": "".join(w.capitalize() for w in route_def.name.replace("-", "_").split("_")),
            "description": route_def.description,
            "pattern": route_def.pattern.value,
            "agent_names": ", ".join(route_def.agents.keys()),
            "created_at": datetime.now().strftime("%Y-%m-%d"),
            "agents": route_def.agents,
            "supervisor_key": supervisor_key,
            "specialists": specialists,
            "aggregator_key": aggregator_key,
            "routing_field": route_def.routing_field or "specialist",
            "required_input_fields": json.dumps(input_required),
            "required_output_fields": json.dumps(output_required),
        }
        
        # Render template
        template = Template(RouteCodeGenerator.SUPERVISOR_MANAGER_TEMPLATE)
        route_code = template.render(**context)
        
        # Generate requirements.txt
        requirements_txt = RouteCodeGenerator._generate_requirements(route_def)
        
        # Generate config.yaml
        config_yaml = RouteCodeGenerator._generate_config(route_def)
        
        # Generate test data
        test_data_json = RouteCodeGenerator._generate_test_data(route_def)
        
        return GeneratedRoute(
            route_code=route_code,
            requirements_txt=requirements_txt,
            config_yaml=config_yaml,
            test_data_json=test_data_json,
            metadata={
                "pattern": route_def.pattern.value,
                "agents": list(route_def.agents.keys()),
                "created_at": datetime.now().isoformat(),
                "version": "v1.0",
            }
        )
    
    @staticmethod
    def _generate_requirements(route_def: RouteDefinition) -> str:
        """Generate requirements.txt"""
        requirements = [
            "semantic-kernel>=0.4.0",
            "azure-ai>=1.0.0",
            "pydantic>=2.0.0",
            "python-dateutil>=2.8.0",
        ]
        
        return "\n".join(requirements) + "\n"
    
    @staticmethod
    def _generate_config(route_def: RouteDefinition) -> str:
        """Generate config.yaml"""
        config = f"""# {route_def.name} - v1.0

name: {route_def.name}
version: v1.0
pattern: {route_def.pattern.value}
description: {route_def.description}

agents:
"""
        for key, agent in route_def.agents.items():
            config += f"  {key}: {agent.name}\n"
        
        config += f"""
timeouts:
  total_seconds: {route_def.timeout_seconds}
  per_agent_seconds: {route_def.per_agent_timeout_seconds}

metadata:
  created_at: {datetime.now().isoformat()}
  created_by: {route_def.csa_email}
"""
        return config
    
    @staticmethod
    def _generate_test_data(route_def: RouteDefinition) -> str:
        """Generate test data"""
        test_data = [
            {
                "name": "test_case_1",
                "input": {
                    "amount": 100000,
                    "loan_type": "mortgage",
                    "credit_score": 750
                },
                "expected": {
                    "decision": "approved"
                }
            },
            {
                "name": "test_case_2",
                "input": {
                    "amount": 30000,
                    "loan_type": "auto",
                    "credit_score": 680
                },
                "expected": {
                    "decision": "approved"
                }
            }
        ]
        
        return json.dumps(test_data, indent=2) + "\n"

