"""Code generation from route definitions"""

import json
from datetime import datetime
from jinja2 import Template
from typing import List
from .models import RouteDefinition, GeneratedRoute, RoutePattern, TestResult

class RouteCodeGenerator:
    """Generates production-ready route code from definitions"""

    SUPERVISOR_MANAGER_TEMPLATE = '''# /routes/{{ route_name }}/route.py
# AUTO-GENERATED by SAFE Route Writer Agent
# DO NOT EDIT - use: safe route update {{ route_name }}

from datetime import datetime
from typing import Dict, Any
import logging
from semantic_kernel import Kernel

logger = logging.getLogger(__name__)

class {{ class_name }}Route:
    """
    {{ route_name }} - {{ description }}

    Pattern: {{ pattern }}
    Agents: {{ agent_names }}
    Created: {{ created_at }}
    """

    def __init__(self, kernel: Kernel):
        self.kernel = kernel
        {% for agent_key, agent in agents.items() %}
        self.{{ agent_key }} = None  # Initialize {{ agent.name }}
        {% endfor %}

    async def invoke(self, request: Dict[str, Any]) -> Dict[str, Any]:
        """Execute {{ route_name }} workflow"""
        start_time = datetime.now()

        try:
            # Validate input
            await self._validate_input(request)
            logger.info(f"Processing request for {{ route_name }}")

            # Route to supervisor
            supervisor_output = await self.{{ supervisor_key }}.invoke(request)

            # Route to appropriate specialist
            routing_field = supervisor_output.get('{{ routing_field }}')

            {% for specialist_key, specialist in specialists.items() %}
            {% if loop.first %}if{% else %}elif{% endif %} routing_field == '{{ specialist_key }}':
                result = await self.{{ specialist_key }}.invoke(request)
            {% endfor %}
            else:
                raise ValueError(f"Unknown routing: {routing_field}")

            # Aggregate results
            final_output = await self.{{ aggregator_key }}.invoke(result)

            # Validate output
            await self._validate_output(final_output)

            elapsed = (datetime.now() - start_time).total_seconds()
            logger.info(f"Completed in {elapsed}s")

            return final_output

        except Exception as e:
            logger.error(f"Route failed: {str(e)}", exc_info=True)
            raise

    async def _validate_input(self, request: Dict[str, Any]) -> None:
        """Validate input against contract"""
        required_fields = {{ required_input_fields }}
        for field in required_fields:
            if field not in request:
                raise ValueError(f"Missing required field: {field}")

    async def _validate_output(self, output: Dict[str, Any]) -> None:
        """Validate output against contract"""
        required_fields = {{ required_output_fields }}
        for field in required_fields:
            if field not in output:
                raise ValueError(f"Missing required output field: {field}")
'''

    FAN_OUT_FAN_IN_TEMPLATE = '''# /routes/{{ route_name }}/route.py
# AUTO-GENERATED by SAFE Route Writer Agent
# DO NOT EDIT - use: safe route update {{ route_name }}

import asyncio
from datetime import datetime
from typing import Dict, Any, List
import logging
from semantic_kernel import Kernel

logger = logging.getLogger(__name__)

class {{ class_name }}Route:
    """
    {{ route_name }} - {{ description }}

    Pattern: {{ pattern }}
    Agents: {{ agent_names }}
    Created: {{ created_at }}
    """

    def __init__(self, kernel: Kernel):
        self.kernel = kernel
        {% for agent_key, agent in agents.items() %}
        self.{{ agent_key }} = None  # Initialize {{ agent.name }}
        {% endfor %}

    async def invoke(self, request: Dict[str, Any]) -> Dict[str, Any]:
        """Execute {{ route_name }} fan-out/fan-in workflow"""
        start_time = datetime.now()

        try:
            await self._validate_input(request)
            logger.info(f"Fan-out to {{ processor_count }} processors for {{ route_name }}")

            # Fan-out: invoke all processors in parallel
            tasks = [
                {% for processor_key in processor_keys %}
                self.{{ processor_key }}.invoke(request),
                {% endfor %}
            ]
            raw_results = await asyncio.gather(*tasks, return_exceptions=True)

            # Filter out failures (fail-open: continue with partial results)
            successful = []
            for i, result in enumerate(raw_results):
                if isinstance(result, Exception):
                    logger.warning(f"Processor {i} failed: {result}")
                else:
                    successful.append(result)

            if not successful:
                raise RuntimeError("All processors failed — cannot aggregate")

            # Fan-in: aggregate results
            final_output = await self.{{ aggregator_key }}.invoke({"results": successful})

            await self._validate_output(final_output)

            elapsed = (datetime.now() - start_time).total_seconds()
            logger.info(f"Completed in {elapsed}s ({len(successful)}/{{ processor_count }} processors succeeded)")

            return final_output

        except Exception as e:
            logger.error(f"Route failed: {str(e)}", exc_info=True)
            raise

    async def _validate_input(self, request: Dict[str, Any]) -> None:
        """Validate input against contract"""
        required_fields = {{ required_input_fields }}
        for field in required_fields:
            if field not in request:
                raise ValueError(f"Missing required field: {field}")

    async def _validate_output(self, output: Dict[str, Any]) -> None:
        """Validate output against contract"""
        required_fields = {{ required_output_fields }}
        for field in required_fields:
            if field not in output:
                raise ValueError(f"Missing required output field: {field}")
'''

    MAP_REDUCE_TEMPLATE = '''# /routes/{{ route_name }}/route.py
# AUTO-GENERATED by SAFE Route Writer Agent
# DO NOT EDIT - use: safe route update {{ route_name }}

import asyncio
from datetime import datetime
from typing import Dict, Any, List
import logging
from semantic_kernel import Kernel

logger = logging.getLogger(__name__)

class {{ class_name }}Route:
    """
    {{ route_name }} - {{ description }}

    Pattern: {{ pattern }}
    Agents: {{ agent_names }}
    Created: {{ created_at }}
    """

    def __init__(self, kernel: Kernel):
        self.kernel = kernel
        {% for agent_key, agent in agents.items() %}
        self.{{ agent_key }} = None  # Initialize {{ agent.name }}
        {% endfor %}

    async def invoke(self, request: Dict[str, Any]) -> Dict[str, Any]:
        """Execute {{ route_name }} map-reduce workflow"""
        start_time = datetime.now()

        try:
            await self._validate_input(request)

            # Split phase
            logger.info(f"Splitting data for {{ route_name }}")
            split_output = await self.{{ splitter_key }}.invoke(request)
            chunks = split_output.get("chunks", [])
            logger.info(f"Split into {len(chunks)} chunks")

            # Map phase: process chunks in parallel
            map_tasks = [
                self.{{ mapper_key }}.invoke({"data_chunk": chunk})
                for chunk in chunks
            ]
            raw_mapped = await asyncio.gather(*map_tasks, return_exceptions=True)

            mapped_results = []
            for i, result in enumerate(raw_mapped):
                if isinstance(result, Exception):
                    logger.warning(f"Mapper failed for chunk {i}: {result}")
                else:
                    mapped_results.append(result.get("mapped_result", result))

            if not mapped_results:
                raise RuntimeError("All map tasks failed — cannot reduce")

            # Reduce phase
            logger.info(f"Reducing {len(mapped_results)} mapped results")
            final_output = await self.{{ reducer_key }}.invoke({"mapped_results": mapped_results})

            await self._validate_output(final_output)

            elapsed = (datetime.now() - start_time).total_seconds()
            logger.info(f"Completed in {elapsed}s")

            return final_output

        except Exception as e:
            logger.error(f"Route failed: {str(e)}", exc_info=True)
            raise

    async def _validate_input(self, request: Dict[str, Any]) -> None:
        """Validate input against contract"""
        required_fields = {{ required_input_fields }}
        for field in required_fields:
            if field not in request:
                raise ValueError(f"Missing required field: {field}")

    async def _validate_output(self, output: Dict[str, Any]) -> None:
        """Validate output against contract"""
        required_fields = {{ required_output_fields }}
        for field in required_fields:
            if field not in output:
                raise ValueError(f"Missing required output field: {field}")
'''

    SEQUENTIAL_PIPELINE_TEMPLATE = '''# /routes/{{ route_name }}/route.py
# AUTO-GENERATED by SAFE Route Writer Agent
# DO NOT EDIT - use: safe route update {{ route_name }}

from datetime import datetime
from typing import Dict, Any
import logging
from semantic_kernel import Kernel

logger = logging.getLogger(__name__)

class {{ class_name }}Route:
    """
    {{ route_name }} - {{ description }}

    Pattern: {{ pattern }}
    Agents: {{ agent_names }}
    Created: {{ created_at }}
    """

    def __init__(self, kernel: Kernel):
        self.kernel = kernel
        {% for agent_key, agent in agents.items() %}
        self.{{ agent_key }} = None  # Initialize {{ agent.name }}
        {% endfor %}

    async def invoke(self, request: Dict[str, Any]) -> Dict[str, Any]:
        """Execute {{ route_name }} sequential-pipeline workflow"""
        start_time = datetime.now()

        try:
            await self._validate_input(request)
            logger.info(f"Starting {{ stage_count }}-stage pipeline for {{ route_name }}")

            # Sequential stage execution — each stage feeds the next
            data = request
            {% for stage_key in stage_keys %}
            logger.debug(f"Executing stage: {{ stage_key }}")
            data = await self.{{ stage_key }}.invoke(data)
            {% endfor %}

            final_output = data
            await self._validate_output(final_output)

            elapsed = (datetime.now() - start_time).total_seconds()
            logger.info(f"Pipeline completed in {elapsed}s")

            return final_output

        except Exception as e:
            logger.error(f"Route failed: {str(e)}", exc_info=True)
            raise

    async def _validate_input(self, request: Dict[str, Any]) -> None:
        """Validate input against contract"""
        required_fields = {{ required_input_fields }}
        for field in required_fields:
            if field not in request:
                raise ValueError(f"Missing required field: {field}")

    async def _validate_output(self, output: Dict[str, Any]) -> None:
        """Validate output against contract"""
        required_fields = {{ required_output_fields }}
        for field in required_fields:
            if field not in output:
                raise ValueError(f"Missing required output field: {field}")
'''

    @staticmethod
    def generate(route_def: RouteDefinition) -> GeneratedRoute:
        """Generate complete route from definition"""

        if route_def.pattern == RoutePattern.SUPERVISOR_MANAGER:
            return RouteCodeGenerator._generate_supervisor_manager(route_def)
        elif route_def.pattern == RoutePattern.FAN_OUT_FAN_IN:
            return RouteCodeGenerator._generate_fan_out_fan_in(route_def)
        elif route_def.pattern == RoutePattern.MAP_REDUCE:
            return RouteCodeGenerator._generate_map_reduce(route_def)
        elif route_def.pattern == RoutePattern.SEQUENTIAL_PIPELINE:
            return RouteCodeGenerator._generate_sequential_pipeline(route_def)
        else:
            raise NotImplementedError(f"Pattern {route_def.pattern} not yet implemented")

    @staticmethod
    def _class_name(route_name: str) -> str:
        return "".join(w.capitalize() for w in route_name.replace("-", "_").split("_"))

    @staticmethod
    def _generate_supervisor_manager(route_def: RouteDefinition) -> GeneratedRoute:
        """Generate supervisor-manager pattern"""

        supervisor_key = "supervisor"
        specialists = {k: v for k, v in route_def.agents.items() if k.startswith("specialist_")}
        aggregator_key = "aggregator"

        supervisor = route_def.agents[supervisor_key]
        input_required = supervisor.input_schema.get("required", [])

        aggregator = route_def.agents[aggregator_key]
        output_required = aggregator.output_schema.get("required", [])

        context = {
            "route_name": route_def.name,
            "class_name": RouteCodeGenerator._class_name(route_def.name),
            "description": route_def.description,
            "pattern": route_def.pattern.value,
            "agent_names": ", ".join(route_def.agents.keys()),
            "created_at": datetime.now().strftime("%Y-%m-%d"),
            "agents": route_def.agents,
            "supervisor_key": supervisor_key,
            "specialists": specialists,
            "aggregator_key": aggregator_key,
            "routing_field": route_def.routing_field or "specialist",
            "required_input_fields": json.dumps(input_required),
            "required_output_fields": json.dumps(output_required),
        }

        template = Template(RouteCodeGenerator.SUPERVISOR_MANAGER_TEMPLATE)
        route_code = template.render(**context)

        return GeneratedRoute(
            route_code=route_code,
            requirements_txt=RouteCodeGenerator._generate_requirements(route_def),
            config_yaml=RouteCodeGenerator._generate_config(route_def),
            test_data_json=RouteCodeGenerator._generate_test_data(route_def),
            metadata={
                "pattern": route_def.pattern.value,
                "agents": list(route_def.agents.keys()),
                "created_at": datetime.now().isoformat(),
                "version": "v1.0",
            }
        )

    @staticmethod
    def _generate_fan_out_fan_in(route_def: RouteDefinition) -> GeneratedRoute:
        """Generate fan-out/fan-in pattern"""

        processor_keys = sorted(k for k in route_def.agents if k.startswith("processor_"))
        aggregator_key = "aggregator"

        first_processor = route_def.agents.get(processor_keys[0]) if processor_keys else None
        input_required = first_processor.input_schema.get("required", []) if first_processor else []

        aggregator = route_def.agents.get(aggregator_key)
        output_required = aggregator.output_schema.get("required", []) if aggregator else []

        context = {
            "route_name": route_def.name,
            "class_name": RouteCodeGenerator._class_name(route_def.name),
            "description": route_def.description,
            "pattern": route_def.pattern.value,
            "agent_names": ", ".join(route_def.agents.keys()),
            "created_at": datetime.now().strftime("%Y-%m-%d"),
            "agents": route_def.agents,
            "processor_keys": processor_keys,
            "processor_count": len(processor_keys),
            "aggregator_key": aggregator_key,
            "required_input_fields": json.dumps(input_required),
            "required_output_fields": json.dumps(output_required),
        }

        template = Template(RouteCodeGenerator.FAN_OUT_FAN_IN_TEMPLATE)
        route_code = template.render(**context)

        return GeneratedRoute(
            route_code=route_code,
            requirements_txt=RouteCodeGenerator._generate_requirements(route_def),
            config_yaml=RouteCodeGenerator._generate_config(route_def),
            test_data_json=RouteCodeGenerator._generate_test_data(route_def),
            metadata={
                "pattern": route_def.pattern.value,
                "agents": list(route_def.agents.keys()),
                "created_at": datetime.now().isoformat(),
                "version": "v1.0",
            }
        )

    @staticmethod
    def _generate_map_reduce(route_def: RouteDefinition) -> GeneratedRoute:
        """Generate map-reduce pattern"""

        splitter_key = "splitter"
        mapper_key = "mapper"
        reducer_key = "reducer"

        splitter = route_def.agents.get(splitter_key)
        input_required = splitter.input_schema.get("required", []) if splitter else []

        reducer = route_def.agents.get(reducer_key)
        output_required = reducer.output_schema.get("required", []) if reducer else []

        context = {
            "route_name": route_def.name,
            "class_name": RouteCodeGenerator._class_name(route_def.name),
            "description": route_def.description,
            "pattern": route_def.pattern.value,
            "agent_names": ", ".join(route_def.agents.keys()),
            "created_at": datetime.now().strftime("%Y-%m-%d"),
            "agents": route_def.agents,
            "splitter_key": splitter_key,
            "mapper_key": mapper_key,
            "reducer_key": reducer_key,
            "required_input_fields": json.dumps(input_required),
            "required_output_fields": json.dumps(output_required),
        }

        template = Template(RouteCodeGenerator.MAP_REDUCE_TEMPLATE)
        route_code = template.render(**context)

        return GeneratedRoute(
            route_code=route_code,
            requirements_txt=RouteCodeGenerator._generate_requirements(route_def),
            config_yaml=RouteCodeGenerator._generate_config(route_def),
            test_data_json=RouteCodeGenerator._generate_test_data(route_def),
            metadata={
                "pattern": route_def.pattern.value,
                "agents": list(route_def.agents.keys()),
                "created_at": datetime.now().isoformat(),
                "version": "v1.0",
            }
        )

    @staticmethod
    def _generate_sequential_pipeline(route_def: RouteDefinition) -> GeneratedRoute:
        """Generate sequential-pipeline pattern"""

        stage_keys = sorted(k for k in route_def.agents if k.startswith("stage_"))

        first_stage = route_def.agents.get(stage_keys[0]) if stage_keys else None
        input_required = first_stage.input_schema.get("required", []) if first_stage else []

        last_stage = route_def.agents.get(stage_keys[-1]) if stage_keys else None
        output_required = last_stage.output_schema.get("required", []) if last_stage else []

        context = {
            "route_name": route_def.name,
            "class_name": RouteCodeGenerator._class_name(route_def.name),
            "description": route_def.description,
            "pattern": route_def.pattern.value,
            "agent_names": ", ".join(route_def.agents.keys()),
            "created_at": datetime.now().strftime("%Y-%m-%d"),
            "agents": route_def.agents,
            "stage_keys": stage_keys,
            "stage_count": len(stage_keys),
            "required_input_fields": json.dumps(input_required),
            "required_output_fields": json.dumps(output_required),
        }

        template = Template(RouteCodeGenerator.SEQUENTIAL_PIPELINE_TEMPLATE)
        route_code = template.render(**context)

        return GeneratedRoute(
            route_code=route_code,
            requirements_txt=RouteCodeGenerator._generate_requirements(route_def),
            config_yaml=RouteCodeGenerator._generate_config(route_def),
            test_data_json=RouteCodeGenerator._generate_test_data(route_def),
            metadata={
                "pattern": route_def.pattern.value,
                "agents": list(route_def.agents.keys()),
                "created_at": datetime.now().isoformat(),
                "version": "v1.0",
            }
        )

    @staticmethod
    def _generate_requirements(route_def: RouteDefinition) -> str:
        """Generate requirements.txt"""
        requirements = [
            "semantic-kernel>=0.4.0",
            "azure-ai>=1.0.0",
            "pydantic>=2.0.0",
            "python-dateutil>=2.8.0",
        ]
        return "\n".join(requirements) + "\n"

    @staticmethod
    def _generate_config(route_def: RouteDefinition) -> str:
        """Generate config.yaml"""
        config = f"""# {route_def.name} - v1.0

name: {route_def.name}
version: v1.0
pattern: {route_def.pattern.value}
description: {route_def.description}

agents:
"""
        for key, agent in route_def.agents.items():
            config += f"  {key}: {agent.name}\n"

        config += f"""
timeouts:
  total_seconds: {route_def.timeout_seconds}
  per_agent_seconds: {route_def.per_agent_timeout_seconds}

metadata:
  created_at: {datetime.now().isoformat()}
  created_by: {route_def.csa_email}
"""
        return config

    @staticmethod
    def _generate_test_data(route_def: RouteDefinition) -> str:
        """Generate pattern-appropriate test data"""
        pattern = route_def.pattern

        if pattern == RoutePattern.SUPERVISOR_MANAGER:
            test_data = [
                {
                    "name": "test_case_1",
                    "input": {"amount": 100000, "loan_type": "mortgage", "credit_score": 750},
                    "expected": {"decision": "approved"},
                },
                {
                    "name": "test_case_2",
                    "input": {"amount": 30000, "loan_type": "auto", "credit_score": 680},
                    "expected": {"decision": "approved"},
                },
            ]
        elif pattern == RoutePattern.FAN_OUT_FAN_IN:
            test_data = [
                {
                    "name": "test_case_1",
                    "input": {"data": {"id": 1, "payload": "sample"}},
                    "expected": {"combined_result": {}},
                },
            ]
        elif pattern == RoutePattern.MAP_REDUCE:
            test_data = [
                {
                    "name": "test_case_1",
                    "input": {"data": [{"item": i} for i in range(5)], "chunk_size": 2},
                    "expected": {"reduced_result": {}},
                },
            ]
        elif pattern == RoutePattern.SEQUENTIAL_PIPELINE:
            test_data = [
                {
                    "name": "test_case_1",
                    "input": {"input_data": {"field": "value"}},
                    "expected": {"output_data": {}},
                },
            ]
        else:
            test_data = [{"name": "test_case_1", "input": {}, "expected": {}}]

        return json.dumps(test_data, indent=2) + "\n"
